### ISSUE TITLE
Transactional email support for registration

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#54]
We should be using some sort of email service to confirm addresses. Mailchimp or sendgrid or something.

**Comment by SriRamanujam** [comment]
Transactional email flow:
1) User registers on website
2) User is sent a confirmation email that somehow links their account (which is currently being held in escrow) to a real account (which is in the DB for real). This method is typically clicking a link provided in the email.
2a) Do we need to set up an escrow table for signed-up-but-not-confirmed users? If so, how should we handle payments? Should the payment itself count as confirmation, and any non-paid accounts cannot log in?
2b) What is the difference between an account in escrow and a fully-authorized account?
3) User clicks the link, which activates a callback in the backend that migrates their data to the real users table and otherwise activates their login.
3a) What do we use as the key for the callback? Ideas include using the BSON Object ID (not sure about security implications) or generating a temporary escrow key during initial registration (probably safer to send to the client in a URL).
